export interface CountryInfo {
  code: string;
  name: string;
  dialCode: string;
  cities: string[];
}

export const COUNTRIES: CountryInfo[] = [
  {
    code: 'IN',
    name: 'India',
    dialCode: '+91',
    cities: [
      'Bengaluru',
      'Mumbai',
      'Delhi / NCR',
      'Hyderabad',
      'Chennai',
      'Pune',
      'Kolkata',
      'Ahmedabad',
      'Jaipur',
      'Chandigarh',
      'Kochi',
      'Coimbatore',
      'Lucknow',
      'Indore',
      'Goa',
    ],
  },
  {
    code: 'US',
    name: 'United States',
    dialCode: '+1',
    cities: [
      'New York',
      'San Francisco / Bay Area',
      'Los Angeles',
      'Chicago',
      'Seattle',
      'Austin',
      'Boston',
      'Miami',
      'Denver',
      'Dallas',
      'Atlanta',
      'San Diego',
      'Washington, D.C.',
      'Phoenix',
      'Philadelphia',
    ],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    dialCode: '+44',
    cities: [
      'London',
      'Manchester',
      'Birmingham',
      'Edinburgh',
      'Glasgow',
      'Bristol',
      'Leeds',
      'Cambridge',
      'Oxford',
      'Liverpool',
      'Belfast',
      'Cardiff',
    ],
  },
  {
    code: 'CA',
    name: 'Canada',
    dialCode: '+1',
    cities: [
      'Toronto',
      'Vancouver',
      'Montreal',
      'Calgary',
      'Ottawa',
      'Edmonton',
      'Quebec City',
      'Winnipeg',
      'Halifax',
      'Victoria',
    ],
  },
  {
    code: 'AU',
    name: 'Australia',
    dialCode: '+61',
    cities: [
      'Sydney',
      'Melbourne',
      'Brisbane',
      'Perth',
      'Adelaide',
      'Gold Coast',
      'Canberra',
      'Hobart',
    ],
  },
  {
    code: 'SG',
    name: 'Singapore',
    dialCode: '+65',
    cities: ['Singapore City', 'Central Region', 'Jurong', 'Tampines', 'Woodlands'],
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    dialCode: '+971',
    cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Al Ain'],
  },
  {
    code: 'DE',
    name: 'Germany',
    dialCode: '+49',
    cities: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg', 'Cologne', 'Stuttgart', 'Düsseldorf'],
  },
  {
    code: 'FR',
    name: 'France',
    dialCode: '+33',
    cities: ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Bordeaux', 'Strasbourg'],
  },
  {
    code: 'JP',
    name: 'Japan',
    dialCode: '+81',
    cities: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Fukuoka', 'Sapporo'],
  },
  {
    code: 'NL',
    name: 'Netherlands',
    dialCode: '+31',
    cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'],
  },
  {
    code: 'CH',
    name: 'Switzerland',
    dialCode: '+41',
    cities: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'],
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    dialCode: '+64',
    cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'],
  },
  {
    code: 'IE',
    name: 'Ireland',
    dialCode: '+353',
    cities: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford'],
  },
  {
    code: 'SE',
    name: 'Sweden',
    dialCode: '+46',
    cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'],
  },
  {
    code: 'ES',
    name: 'Spain',
    dialCode: '+34',
    cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Malaga', 'Bilbao'],
  },
  {
    code: 'IT',
    name: 'Italy',
    dialCode: '+39',
    cities: ['Rome', 'Milan', 'Florence', 'Naples', 'Turin', 'Bologna'],
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    dialCode: '+966',
    cities: ['Riyadh', 'Jeddah', 'Dammam', 'Mecca', 'Medina', 'Khobar'],
  },
  {
    code: 'ZA',
    name: 'South Africa',
    dialCode: '+27',
    cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
  },
  {
    code: 'MY',
    name: 'Malaysia',
    dialCode: '+60',
    cities: ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Petaling Jaya'],
  },
  {
    code: 'PH',
    name: 'Philippines',
    dialCode: '+63',
    cities: ['Manila', 'Quezon City', 'Cebu City', 'Davao City'],
  },
  {
    code: 'BR',
    name: 'Brazil',
    dialCode: '+55',
    cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Belo Horizonte'],
  },
  {
    code: 'MX',
    name: 'Mexico',
    dialCode: '+52',
    cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Cancún'],
  },
  {
    code: 'KR',
    name: 'South Korea',
    dialCode: '+82',
    cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon'],
  },
  {
    code: 'NO',
    name: 'Norway',
    dialCode: '+47',
    cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
  },
  {
    code: 'DK',
    name: 'Denmark',
    dialCode: '+45',
    cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'],
  },
  {
    code: 'FI',
    name: 'Finland',
    dialCode: '+358',
    cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'],
  },
  {
    code: 'AT',
    name: 'Austria',
    dialCode: '+43',
    cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
  },
  {
    code: 'BE',
    name: 'Belgium',
    dialCode: '+32',
    cities: ['Brussels', 'Antwerp', 'Ghent', 'Bruges'],
  },
  {
    code: 'IL',
    name: 'Israel',
    dialCode: '+972',
    cities: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Rishon LeZion'],
  },
  {
    code: 'GLOBAL',
    name: 'Other Country',
    dialCode: '+1',
    cities: ['Other City'],
  },
];
